/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        white: 'var(--cor-secundaria)',
        black: 'var(--cor-footer)',
        gray: {
          50: 'var(--cor-fundo)',
          100: 'var(--cor-borda)',
          200: 'var(--cor-borda)',
          300: 'var(--cor-cinza-azulado)',
          400: 'var(--cor-cinza-medio)',
          500: 'var(--cor-texto-mutado)',
          600: 'var(--cor-texto-mutado)',
          700: 'var(--cor-texto)',
          800: 'var(--cor-texto)',
          900: 'var(--cor-footer)',
        },
        slate: {
          50: 'var(--cor-fundo)',
          100: 'var(--cor-borda)',
          200: 'var(--cor-cinza-claro)',
          300: 'var(--cor-cinza-azulado)',
          400: 'var(--cor-cinza-medio)',
          500: 'var(--cor-texto-mutado)',
          600: 'var(--cor-texto-mutado)',
          700: 'var(--cor-texto)',
          800: 'var(--cor-escuro-dashboard)',
          900: 'var(--cor-footer)',
        },
        primary: {
          50: 'var(--cor-laranja-claro-fundo)',
          100: 'var(--cor-laranja-claro-borda)',
          500: 'var(--cor-primaria)',
          600: 'var(--cor-primaria-hover)',
          700: 'var(--cor-primaria)',
          800: 'var(--cor-primaria-hover)',
          900: 'var(--cor-escuro-quente)',
        },
        blue: {
          50: 'var(--cor-laranja-claro-fundo)',
          100: 'var(--cor-laranja-claro-borda)',
          200: 'var(--cor-texto-claro)',
          300: 'var(--cor-cinza-azulado)',
          400: 'var(--cor-cinza-medio)',
          500: 'var(--cor-primaria)',
          600: 'var(--cor-primaria-hover)',
          700: 'var(--cor-primaria)',
          800: 'var(--cor-primaria-hover)',
          900: 'var(--cor-escuro-quente)',
          950: 'var(--cor-escuro-dashboard)',
        },
        amber: {
          50: 'var(--cor-laranja-claro-fundo)',
          100: 'var(--cor-laranja-claro-borda)',
          200: 'var(--cor-laranja-claro-borda)',
          400: 'var(--cor-primaria)',
          500: 'var(--cor-primaria)',
          600: 'var(--cor-primaria-hover)',
          700: 'var(--cor-primaria-hover)',
          800: 'var(--cor-escuro-quente)',
        },
        yellow: {
          100: 'var(--cor-laranja-claro-fundo)',
          800: 'var(--cor-primaria-hover)',
        },
        green: {
          50: 'var(--cor-sucesso-fundo)',
          100: 'var(--cor-sucesso-fundo)',
          300: 'var(--cor-sucesso-fundo)',
          400: 'var(--cor-sucesso-texto)',
          500: 'var(--cor-sucesso-texto)',
          600: 'var(--cor-sucesso-texto)',
          700: 'var(--cor-sucesso-texto)',
          800: 'var(--cor-sucesso-texto)',
        },
        red: {
          50: 'var(--cor-erro-fundo)',
          100: 'var(--cor-erro-fundo)',
          400: 'var(--cor-erro-borda)',
          500: 'var(--cor-erro-alt)',
          600: 'var(--cor-erro)',
          700: 'var(--cor-erro)',
          800: 'var(--cor-erro)',
        },
        purple: {
          50: 'var(--cor-laranja-claro-fundo)',
          100: 'var(--cor-laranja-claro-borda)',
          600: 'var(--cor-primaria)',
          700: 'var(--cor-primaria-hover)',
        },
        drm: {
          blue: 'var(--cor-escuro-dashboard)',
          lightblue: 'var(--cor-primaria)',
          gold: 'var(--cor-primaria)',
        }
      }
    },
  },
  plugins: [],
}
